modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="rpgmod"
version="1.0.0"
displayName="rpgmod" 
authors="Chiveshorya and Xomchik"

[[dependencies.rpgmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




